command: /usr/bin/python /u/pedronis/PyPy/dist/pypy/tool/alarm.py 900 /u/pedronis/PyPy/dist/pypy/interpreter/py.py --oldstyle /u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_logging.py
run by: pedronis@ratthing-b246
sys.platform: linux2
sys.version_info: (2, 3, 5, 'final', 0)
startdate: Thu Apr 28 01:52:03 2005
pypy-revision: 11549
OUTPUT TEST
see output in: /u/pedronis/PyPy/dist/lib-python-2.3.4/test/result/test_logging.out
============================================================
faking <type 'unicode'>
faking <type 'module'>
faking <type 'file'>
faking <type 'posix.stat_result'>
faking <type 'posix.statvfs_result'>
faking <type '_sre.SRE_Pattern'>
faking <type 'function'>
faking <type 'instancemethod'>
faking <type '_sre.SRE_Match'>
faking <type '_socket.socket'>
faking <type 'classobj'>
faking <type 'PyCObject'>
Traceback (application-level):
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_logging.py", line 29 in ?
import socket, threading, time
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/threading.py", line 6 in ?
    import thread
ImportError: thread
FAILED: test output differs
========================== closed ==========================
execution time: 15.7029800415 seconds
exit status: 1
