command: /usr/bin/python /u/pedronis/PyPy/dist/pypy/tool/alarm.py 900 /u/pedronis/PyPy/dist/pypy/interpreter/py.py --oldstyle /u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_threaded_import.py
run by: pedronis@ratthing-b246
sys.platform: linux2
sys.version_info: (2, 3, 5, 'final', 0)
startdate: Thu Apr 28 14:45:19 2005
pypy-revision: 11549
============================================================
faking <type 'unicode'>
faking <type 'module'>
Traceback (application-level):
  File "/u/pedronis/PyPy/dist/lib-python-2.3.4/test/test_threaded_import.py", line 8 in ?
import thread
ImportError: thread
========================== closed ==========================
execution time: 1.15094518661 seconds
exit status: 1
