command: /usr/bin/python /home/arigo/pypysrc/pypy/tool/alarm.py 900 /home/arigo/pypysrc/pypy/interpreter/py.py --oldstyle /home/arigo/pypysrc/lib-python-2.3.4/test/test_dl.py
run by: arigo@tismerysoft.de
sys.platform: linux2
sys.version_info: (2, 3, 5, 'final', 0)
startdate: Thu Apr 28 02:36:06 2005
pypy-revision: 11518
============================================================
faking <type 'unicode'>
faking <type 'module'>
Traceback (application-level):
  File "/home/arigo/pypysrc/lib-python-2.3.4/test/test_dl.py", line 6 in ?
import dl
ImportError: dl
========================== closed ==========================
execution time: 0.862523078918 seconds
exit status: 1
